services:
  front-end:
    image: node:18-alpine
    command: sh -c "npm install && npm start"
    ports:
      - 3000:3000
    working_dir: /orca-beta-front-end
    volumes:
      - ./orca-beta-front-end/:/orca-beta-front-end
  webserver:
    image: nginx:latest
    ports:
    - 80:80
    - 443:443
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro